# Generated by Django 2.1 on 2018-08-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
