# Generated by Django 2.1 on 2018-08-27 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_invoice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='date_added',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
