# Generated by Django 2.0.7 on 2019-03-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_auto_20190320_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_net',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
