# Generated by Django 2.0.7 on 2019-03-20 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_auto_20190320_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_net',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tax',
        ),
    ]
