# Generated by Django 2.0.7 on 2019-03-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_auto_20190320_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='tax',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
