# Generated by Django 2.0.7 on 2019-03-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoiceitem_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_net',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
