# Generated by Django 2.1 on 2018-10-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='customer',
        ),
    ]
