# Generated by Django 2.1 on 2018-10-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20180818_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='accountant_for_client_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='accountant_for_client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='accountant_for_client_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='point_of_contact_for_client_email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='point_of_contact_for_client_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='point_of_contact_for_client_phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
