# Generated by Django 2.0.7 on 2019-03-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20181026_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='landline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
