# Generated by Django 2.1 on 2018-10-17 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('customer_name', models.CharField(max_length=25)),
                ('company_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('service_description', models.CharField(max_length=150)),
                ('service_quantity', models.IntegerField()),
                ('service_rate', models.FloatField()),
                ('service_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('GBP', 'GBP'), ('EUR', 'EUR')], max_length=4)),
                ('service_exch_rate', models.FloatField(default=1.0)),
                ('service_total', models.FloatField(default=0.0)),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
