# Generated by Django 2.1 on 2018-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0003_quotation_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='service_total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
