# Generated by Django 2.1 on 2018-10-27 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0004_auto_20181026_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=1)),
                ('currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='INR', max_length=3)),
                ('rate', models.FloatField(default=1.0)),
                ('exchange_rate', models.FloatField(default=1.0)),
                ('tax_rate', models.FloatField(default=18.0)),
                ('total', models.FloatField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotations.Quotation')),
            ],
        ),
    ]
