# Generated by Django 2.1 on 2018-10-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0005_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='revision_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
