# Generated by Django 2.1 on 2018-10-27 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0006_quotation_revision_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='service_currency',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='service_exch_rate',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='service_quantity',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='service_rate',
        ),
    ]
